# Generated by Django 6.0.6 on 2026-07-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('status', models.BooleanField()),
                ('address', models.CharField(max_length=255)),
                ('stream_id', models.TextField()),
                ('longitude', models.TextField()),
                ('zone_type', models.TextField()),
                ('stream_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DogEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera_id', models.TextField()),
                ('dogs_count', models.IntegerField()),
                ('persson_detected', models.IntegerField()),
                ('distance_to_person', models.IntegerField()),
                ('is_pack', models.FloatField()),
                ('is_dangerous', models.FloatField()),
                ('confidence', models.FloatField()),
                ('detected_at', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.TextField()),
                ('event_type', models.TextField()),
                ('priority', models.TextField()),
                ('confidence', models.FloatField()),
                ('status', models.BooleanField()),
                ('source_type', models.TextField()),
                ('source_event_id', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.TextField()),
                ('event_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LogsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.TextField()),
                ('event_type', models.TextField()),
                ('priority', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.TextField()),
                ('dogs_count', models.IntegerField(default=0)),
                ('trash_count', models.IntegerField(default=0)),
                ('suspicious_count', models.IntegerField(default=0)),
                ('count_person', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PublicSafetyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.TextField()),
                ('event_type', models.TextField()),
                ('priority', models.TextField()),
                ('confidence', models.FloatField()),
                ('metadata', models.TextField()),
                ('is_send_to_core', models.IntegerField()),
                ('sent_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('value', models.TextField()),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings_API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_dogs', models.IntegerField()),
                ('time_object', models.IntegerField()),
                ('cooldown_events', models.IntegerField()),
                ('min_confidence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SuspiciousObjectEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.TextField()),
                ('object_type', models.TextField()),
                ('standing_time_minutes', models.IntegerField()),
                ('people_nearby', models.IntegerField()),
                ('is_suspicious', models.FloatField()),
                ('confidence', models.IntegerField()),
                ('priority', models.TextField()),
                ('detected_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TrashEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('count_trashed', models.IntegerField()),
            ],
        ),
    ]
