# Generated by Django 6.0.6 on 2026-07-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.TextField()),
                ('event_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LogsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.TextField()),
                ('event_type', models.TextField()),
                ('priority', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='dogevents',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='trashevent',
            name='status',
            field=models.BooleanField(),
        ),
    ]
