# Generated by Django 6.0.6 on 2026-07-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_logs_logsevent_alter_dogevents_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings_API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_dogs', models.IntegerField()),
                ('time_object', models.IntegerField()),
                ('cooldown_events', models.IntegerField()),
                ('min_confidence', models.IntegerField()),
            ],
        ),
    ]
